name: build dist

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: certseeds/common-actions/actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: certseeds/common-actions/actions/setup-nodejs@v1

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - uses: certseeds/common-actions/actions/upload-artifact@v1
        with:
          name: wh40k-icon
          path: ./dist
          compression-level: 9
          retention-days: 12

      - uses: certseeds/common-actions/actions/deploy-npm@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.NPM_TOKEN }}
