name: build dist

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: wh40k-icon
          path: ./dist
          compression-level: 9
          retention-days: 12

      - name: Bump version with date prefix
        run: |
          DATE=$(date +'%Y%m%d%H%M%S')
          npm version prerelease --preid=$DATE --no-git-tag-version
          echo "Updated version to $(cat package.json | grep version)"
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish package
        run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
